# Generated by Django 4.0.3 on 2022-03-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contributor',
            new_name='contributors',
        ),
    ]
